'use strict';

// Presets autorais da Lumi. As referências são categorias estéticas amplas — nenhum
// texto, asset ou componente de terceiros é incorporado neste catálogo.
const presets = [
  {
    id: 'signal-noir',
    name: 'Signal Noir',
    version: 1,
    mode: 'dark',
    summary: 'Minimalismo arquitetônico escuro com tipografia precisa e sinais cromáticos pontuais.',
    tags: ['dark', 'minimal', 'dashboard', 'saas', 'technical'],
    suitableFor: ['SaaS B2B', 'painéis operacionais', 'produtos de IA', 'ferramentas de desenvolvimento'],
    direction: [
      'A interface deve parecer uma sala de controle silenciosa: escura, precisa e sem ornamento gratuito.',
      'A cor de destaque comunica estado e ação; ela nunca vira decoração de fundo.',
      'Densidade moderada, alinhamento rigoroso e contraste de camadas substituem sombras pesadas.',
    ],
    colors: { canvas: '#080A0F', surface: '#10131A', elevated: '#171B24', text: '#F4F7FB', muted: '#8C96A8', border: '#252B37', primary: '#7C5CFF', secondary: '#28D7A1', danger: '#FF667A' },
    typography: { display: 'Space Grotesk', body: 'Inter', mono: 'JetBrains Mono', displayWeight: 650, bodyWeight: 400, tracking: '-0.025em' },
    geometry: { radius: '12px', controlRadius: '9px', border: '1px', shadow: '0 18px 60px rgba(0, 0, 0, .28)', density: 'comfortable' },
    layout: ['Grid de 12 colunas com margens amplas.', 'Sidebar estreita e estável em aplicações densas.', 'Cards agrupam uma decisão ou métrica, nunca conteúdo arbitrário.'],
    components: ['Botão primário sólido e compacto; secundário apenas contornado.', 'Inputs escuros com foco violeta de 2px e label sempre visível.', 'Tabelas usam divisores discretos, números monoespaçados e cabeçalho fixo.'],
    motion: ['Transições de 160–220ms.', 'Hover move no máximo 2px.', 'Gráficos podem revelar dados progressivamente, respeitando prefers-reduced-motion.'],
    avoid: ['gradientes arco-íris', 'glow em todos os elementos', 'cards sem função', 'texto cinza de baixo contraste'],
    preview: { composition: 'dashboard', eyebrow: 'SYSTEM / 07', headline: 'Clarity at signal speed' },
  },
  {
    id: 'ember-grid',
    name: 'Ember Grid',
    version: 1,
    mode: 'dark',
    summary: 'Sistema industrial de alta densidade aquecido por laranja-ember sobre grafite.',
    tags: ['dark', 'industrial', 'developer-tools', 'data', 'security'],
    suitableFor: ['observabilidade', 'infraestrutura', 'segurança', 'ferramentas técnicas'],
    direction: ['Superfícies lembram equipamento industrial bem mantido.', 'Linhas, coordenadas e labels monoespaçadas dão estrutura.', 'O laranja marca ignição, risco ou ação principal, nunca conteúdo passivo.'],
    colors: { canvas: '#0D0E0F', surface: '#171819', elevated: '#202224', text: '#F2EEE8', muted: '#9A958D', border: '#343536', primary: '#FF6A1A', secondary: '#F5B942', danger: '#FF3D4F' },
    typography: { display: 'Archivo', body: 'IBM Plex Sans', mono: 'IBM Plex Mono', displayWeight: 700, bodyWeight: 400, tracking: '-0.03em' },
    geometry: { radius: '4px', controlRadius: '3px', border: '1px', shadow: '0 14px 44px rgba(0, 0, 0, .34)', density: 'dense' },
    layout: ['Grid modular com linhas visíveis e ritmo de 8px.', 'Painéis podem encostar, desde que divisores organizem a hierarquia.', 'Números e status ocupam posições previsíveis.'],
    components: ['Botões parecem comandos físicos, com estado pressionado claro.', 'Badges usam caixa alta e tracking amplo.', 'Logs e terminais têm contraste alto e seleção legível.'],
    motion: ['Feedback imediato de 120–180ms.', 'Barras de progresso se movem linearmente.', 'Nada flutua ou quica.'],
    avoid: ['raios excessivos', 'glassmorphism', 'ilustrações fofas', 'espaçamento aleatório'],
    preview: { composition: 'terminal', eyebrow: 'NODE 04 / ACTIVE', headline: 'Infrastructure, under control' },
  },
  {
    id: 'paper-orbit',
    name: 'Paper Orbit',
    version: 1,
    mode: 'light',
    summary: 'Editorial tecnológico em papel quente, serifas marcantes e um instante prismático.',
    tags: ['light', 'editorial', 'serif', 'ai', 'content'],
    suitableFor: ['sites institucionais', 'pesquisa', 'publicações', 'produtos de IA premium'],
    direction: ['A página deve parecer uma publicação contemporânea, não um dashboard genérico.', 'Títulos serifados criam autoridade; a UI permanece limpa e pragmática.', 'Momentos cromáticos aparecem como capa, gráfico ou detalhe editorial.'],
    colors: { canvas: '#F3EFE6', surface: '#FBF8F1', elevated: '#FFFFFF', text: '#191815', muted: '#746F66', border: '#D8D0C3', primary: '#5548E8', secondary: '#E66A9B', danger: '#B93645' },
    typography: { display: 'Cormorant Garamond', body: 'Manrope', mono: 'DM Mono', displayWeight: 600, bodyWeight: 400, tracking: '-0.035em' },
    geometry: { radius: '2px', controlRadius: '999px', border: '1px', shadow: '0 16px 46px rgba(61, 45, 23, .10)', density: 'comfortable' },
    layout: ['Colunas editoriais assimétricas com bastante respiro.', 'Texto corrido limitado a 68 caracteres por linha.', 'Imagens e dados podem romper a grade deliberadamente.'],
    components: ['CTAs em pílula pequena contrastam com layouts retilíneos.', 'Cards se comportam como blocos de artigo, com bordas finas.', 'Citações e números-chave usam a fonte display.'],
    motion: ['Entradas suaves de 350–500ms.', 'Imagens podem revelar por máscara simples.', 'Links usam sublinhado animado, sem deslocar layout.'],
    avoid: ['muitos cards iguais', 'ícones coloridos em excesso', 'sombras escuras', 'parágrafos muito largos'],
    preview: { composition: 'editorial', eyebrow: 'FIELD NOTES / 2026', headline: 'Intelligence deserves a point of view' },
  },
  {
    id: 'cirrus-soft',
    name: 'Cirrus Soft',
    version: 1,
    mode: 'light',
    summary: 'SaaS luminoso e calmo, com superfícies de nuvem, controles arredondados e acento serifado.',
    tags: ['light', 'saas', 'soft', 'friendly', 'productivity'],
    suitableFor: ['produtividade', 'colaboração', 'onboarding', 'apps de bem-estar'],
    direction: ['A sensação é leve e segura, com profundidade quase atmosférica.', 'A interface usa linguagem humana e reduz ansiedade operacional.', 'A serifa aparece apenas em palavras de ênfase, nunca no corpo inteiro.'],
    colors: { canvas: '#EDF5FA', surface: '#F8FCFF', elevated: '#FFFFFF', text: '#17232C', muted: '#667784', border: '#D7E5ED', primary: '#3269E8', secondary: '#77B8D8', danger: '#D64B66' },
    typography: { display: 'Plus Jakarta Sans', body: 'Inter', mono: 'DM Mono', displayWeight: 650, bodyWeight: 400, tracking: '-0.03em' },
    geometry: { radius: '22px', controlRadius: '999px', border: '1px', shadow: '0 22px 70px rgba(50, 105, 142, .13)', density: 'spacious' },
    layout: ['Containers largos com ilhas de conteúdo bem separadas.', 'Seções respiram entre 88 e 120px no desktop.', 'Formulários evitam mais de duas colunas.'],
    components: ['Botões em pílula têm área de toque mínima de 44px.', 'Cards brancos flutuam sutilmente sobre o azul-neblina.', 'Avatares e estados colaborativos usam contornos, não sombras fortes.'],
    motion: ['Transições orgânicas de 220–320ms.', 'Hover eleva 3px e clareia a borda.', 'Loading usa skeleton suave sem brilho agressivo.'],
    avoid: ['azul corporativo saturado em grandes áreas', 'bordas pretas', 'densidade de dashboard financeiro', 'animações elásticas'],
    preview: { composition: 'airy', eyebrow: 'CALM WORKSPACE', headline: 'Make space for better work' },
  },
  {
    id: 'field-notes',
    name: 'Field Notes',
    version: 1,
    mode: 'light',
    summary: 'Caderno editorial com papel creme, linhas de tinta e componentes que parecem anotações organizadas.',
    tags: ['light', 'notebook', 'playful', 'education', 'journal'],
    suitableFor: ['educação', 'journaling', 'planejamento', 'portfólios pessoais'],
    direction: ['A interface remete a um caderno usado com cuidado, nunca a uma caricatura escolar.', 'Linhas e margem ajudam a organizar; não devem prejudicar leitura.', 'Pequenas imperfeições podem aparecer em ícones ou destaques, não na tipografia do corpo.'],
    colors: { canvas: '#F4EEDC', surface: '#FBF7EA', elevated: '#FFFDF6', text: '#17345B', muted: '#68768A', border: '#B9C9D9', primary: '#225AA6', secondary: '#D84A52', danger: '#B82F3A' },
    typography: { display: 'Bitter', body: 'Nunito Sans', mono: 'Courier Prime', displayWeight: 700, bodyWeight: 400, tracking: '-0.015em' },
    geometry: { radius: '6px', controlRadius: '4px', border: '1px', shadow: '3px 4px 0 rgba(23, 52, 91, .12)', density: 'comfortable' },
    layout: ['Ritmo vertical alinhado a uma grade de 24px.', 'Margem lateral vermelha pode marcar navegação ou prioridade.', 'Notas rápidas aparecem como cartões menores sobre o papel.'],
    components: ['Checkboxes lembram quadrados desenhados, mas mantêm foco acessível.', 'Tabs parecem marcadores de página.', 'Callouts usam papel colorido sólido e um pequeno ícone linear.'],
    motion: ['Elementos entram com fade curto e rotação máxima de 0.5°.', 'Checkbox confirma com traço desenhado em até 220ms.', 'Respeitar reduced motion removendo rotação.'],
    avoid: ['fontes manuscritas no corpo', 'texturas pesadas', 'papel amassado fotorrealista', 'inclinações aleatórias'],
    preview: { composition: 'notebook', eyebrow: 'WEEK 32 / NOTES', headline: 'Ideas worth keeping close' },
  },
  {
    id: 'ultraviolet-studio',
    name: 'Ultraviolet Studio',
    version: 1,
    mode: 'dark',
    summary: 'Estúdio criativo escuro com imagens saturadas, gradientes líquidos e ornamento cósmico controlado.',
    tags: ['dark', 'creative', 'music', 'portfolio', 'gradient'],
    suitableFor: ['estúdios criativos', 'música', 'moda', 'portfólios experimentais'],
    direction: ['O produto deve parecer uma capa cultural viva, com foco claro em imagem e tipografia.', 'Gradientes ocupam momentos especiais; conteúdo utilitário volta ao preto profundo.', 'Ornamentos têm função de enquadramento, não de preenchimento.'],
    colors: { canvas: '#0B0712', surface: '#161020', elevated: '#21162E', text: '#FFF6FB', muted: '#A89CB3', border: '#362641', primary: '#C649FF', secondary: '#FF4E8A', danger: '#FF4768' },
    typography: { display: 'Syne', body: 'Manrope', mono: 'Space Mono', displayWeight: 750, bodyWeight: 400, tracking: '-0.04em' },
    geometry: { radius: '18px', controlRadius: '999px', border: '1px', shadow: '0 28px 90px rgba(147, 43, 220, .22)', density: 'spacious' },
    layout: ['Composições assimétricas com um único foco visual dominante.', 'Imagens usam proporções editoriais consistentes.', 'Texto de apoio permanece em blocos compactos e legíveis.'],
    components: ['CTA principal pode usar gradiente; demais controles ficam neutros.', 'Cards de projeto revelam metadados no hover.', 'Cursores e ícones decorativos nunca substituem labels.'],
    motion: ['Imagens ampliam lentamente em 450–650ms.', 'Gradientes podem deslocar de forma quase imperceptível.', 'Sem loops rápidos ou flashes.'],
    avoid: ['gradiente em cada botão', 'texto sobre imagem sem overlay', 'efeitos WebGL sem fallback', 'tipografia ilegível'],
    preview: { composition: 'studio', eyebrow: 'STUDIO / SELECTED WORK', headline: 'Culture in full spectrum' },
  },
  {
    id: 'shell-95',
    name: 'Shell 95',
    version: 1,
    mode: 'light',
    summary: 'Desktop retrô reinterpretado com chrome prateado, barras de título e precisão pixelar.',
    tags: ['retro', 'desktop', 'pixel', 'playful', 'portfolio'],
    suitableFor: ['sites experimentais', 'portfólios', 'jogos indie', 'ferramentas nostálgicas'],
    direction: ['Evocar software dos anos 90 sem copiar interfaces proprietárias.', 'A nostalgia vive na geometria e nos estados; a usabilidade continua moderna.', 'Janelas organizam conteúdo em vez de virar decoração caótica.'],
    colors: { canvas: '#3C8B87', surface: '#C6C6C6', elevated: '#E4E4E4', text: '#111111', muted: '#505050', border: '#707070', primary: '#172A88', secondary: '#00847F', danger: '#A8202A' },
    typography: { display: 'Pixelify Sans', body: 'Tahoma', mono: 'IBM Plex Mono', displayWeight: 700, bodyWeight: 400, tracking: '0' },
    geometry: { radius: '0px', controlRadius: '0px', border: '2px', shadow: '3px 3px 0 rgba(0, 0, 0, .45)', density: 'dense' },
    layout: ['Janelas têm título, conteúdo e ações claramente separados.', 'Desktop pode usar grid livre apenas no topo; conteúdo interno segue fluxo normal.', 'Em mobile, janelas tornam-se blocos empilhados em largura total.'],
    components: ['Botões têm bevel claro/escuro e estado pressionado invertido.', 'Menus exibem foco e atalhos por teclado.', 'Ícones são simples e pixel-tight, com aria-label.'],
    motion: ['Mudanças de estado quase instantâneas, 80–120ms.', 'Janelas podem abrir com scale de 0.98 sem bounce.', 'Nada pisca automaticamente.'],
    avoid: ['usar logotipos de sistemas reais', 'texto serrilhado propositalmente', 'cursores inacessíveis', 'janelas sobrepostas no mobile'],
    preview: { composition: 'retro', eyebrow: 'LUMI_OS / READY', headline: 'A familiar future' },
  },
  {
    id: 'moss-ledger',
    name: 'Moss Ledger',
    version: 1,
    mode: 'light',
    summary: 'Sistema quente e orientado a dados com papel creme, verde profundo e acento lima elétrico.',
    tags: ['light', 'data', 'sustainability', 'finance', 'warm'],
    suitableFor: ['climate tech', 'finanças responsáveis', 'relatórios', 'produtos de dados'],
    direction: ['Confiabilidade vem da estrutura editorial e dos números, não de estética bancária genérica.', 'Verde profundo ancora a página; lima sinaliza oportunidade ou progresso.', 'Superfícies claras mantêm longas sessões de leitura confortáveis.'],
    colors: { canvas: '#F1EBD9', surface: '#FAF6E9', elevated: '#FFFFFF', text: '#18362B', muted: '#6E786D', border: '#CBD0BC', primary: '#1E5A43', secondary: '#B9F227', danger: '#B84943' },
    typography: { display: 'DM Serif Display', body: 'DM Sans', mono: 'Roboto Mono', displayWeight: 500, bodyWeight: 400, tracking: '-0.025em' },
    geometry: { radius: '10px', controlRadius: '999px', border: '1px', shadow: '0 16px 50px rgba(24, 54, 43, .12)', density: 'comfortable' },
    layout: ['Seções alternam papel e painéis verde-profundo.', 'Dados principais usam grade consistente e alinhamento decimal.', 'Narrativa e visualização de dados nunca competem na mesma coluna.'],
    components: ['Cards de métrica incluem contexto temporal e unidade.', 'Gráficos usam no máximo cinco cores semanticamente estáveis.', 'Filtros aparecem em uma barra clara e previsível.'],
    motion: ['Contadores podem animar uma vez em 350ms.', 'Gráficos revelam séries sem elasticidade.', 'Hover de dados destaca também legenda correspondente.'],
    avoid: ['verde em todos os textos', 'ícones de folha genéricos', 'gráficos sem legenda', 'acento lima em grandes superfícies'],
    preview: { composition: 'finance', eyebrow: 'IMPACT REPORT / Q3', headline: 'Growth with a longer horizon' },
  },
  {
    id: 'nocturne-pill',
    name: 'Nocturne Pill',
    version: 1,
    mode: 'dark',
    summary: 'SaaS profundo em índigo, brilho violeta ambiente e controles ultra-arredondados.',
    tags: ['dark', 'saas', 'violet', 'productivity', 'ambient'],
    suitableFor: ['produtividade', 'IA generativa', 'apps de conteúdo', 'ferramentas pessoais'],
    direction: ['A atmosfera é noturna e confortável, sem sacrificar contraste.', 'Pílulas agrupam ações relacionadas e ajudam na orientação.', 'O brilho fica atrás de superfícies importantes, nunca atrás de texto longo.'],
    colors: { canvas: '#0B0B1A', surface: '#14142A', elevated: '#1D1B38', text: '#F5F3FF', muted: '#9A96B6', border: '#312D52', primary: '#8C6BFF', secondary: '#4FC7D9', danger: '#FF6688' },
    typography: { display: 'Sora', body: 'Inter', mono: 'JetBrains Mono', displayWeight: 650, bodyWeight: 400, tracking: '-0.035em' },
    geometry: { radius: '24px', controlRadius: '999px', border: '1px', shadow: '0 24px 80px rgba(93, 69, 211, .22)', density: 'comfortable' },
    layout: ['Conteúdo central com largura controlada e navegação flutuante.', 'Grupos de ações vivem em cápsulas, separados do conteúdo.', 'Painéis laterais usam camadas índigo distintas.'],
    components: ['Botões primários têm preenchimento violeta e foco claro.', 'Composer e campos longos usam raio menor que os controles curtos.', 'Menus flutuantes mantêm blur discreto e borda visível.'],
    motion: ['Entradas de 260–380ms com fade e translate pequeno.', 'Pílulas selecionadas deslizam indicador interno.', 'Glows não pulsam continuamente.'],
    avoid: ['preto puro', 'blur em toda a página', 'glow sobre texto', 'controles sem estado selecionado'],
    preview: { composition: 'airy-dark', eyebrow: 'FOCUS MODE', headline: 'Your quiet place to create' },
  },
  {
    id: 'atlas-pixel',
    name: 'Atlas Pixel',
    version: 1,
    mode: 'light',
    summary: 'Editorial pixel-art para mundos, jogos e mapas digitais sobre pergaminho quente.',
    tags: ['pixel', 'editorial', 'game', 'map', 'light'],
    suitableFor: ['jogos indie', 'worldbuilding', 'comunidades', 'documentação de universos'],
    direction: ['Pixel art é o conteúdo heroico; UI de suporte continua clara e econômica.', 'Blocos tipográficos grandes criam ritmo de pôster.', 'A paleta lembra mapa impresso, com acentos de bioma bem definidos.'],
    colors: { canvas: '#E8D5A8', surface: '#F3E5BE', elevated: '#FFF1CC', text: '#2A241C', muted: '#776B55', border: '#9D8B68', primary: '#315B4A', secondary: '#C65B35', danger: '#A53E38' },
    typography: { display: 'Press Start 2P', body: 'Atkinson Hyperlegible', mono: 'VT323', displayWeight: 400, bodyWeight: 400, tracking: '-0.01em' },
    geometry: { radius: '0px', controlRadius: '0px', border: '2px', shadow: '4px 4px 0 rgba(42, 36, 28, .18)', density: 'comfortable' },
    layout: ['Hero combina mapa ou cena pixelada com título em bloco.', 'Cards formam inventário modular em grid.', 'Corpo de texto usa fonte altamente legível, nunca pixelada.'],
    components: ['Botões lembram placas ou slots, com foco de alto contraste.', 'Badges identificam bioma, raridade ou categoria com texto além da cor.', 'Tooltips têm atraso curto e não cobrem o alvo.'],
    motion: ['Movimento usa passos discretos quando decorativo.', 'Interfaces críticas continuam suaves e previsíveis.', 'Desativar animações ambientais em reduced motion.'],
    avoid: ['fonte pixel no corpo', 'sprites copiados de jogos', 'paleta sem contraste', 'animação a 12fps em controles'],
    preview: { composition: 'pixel', eyebrow: 'REGION 08 / DISCOVERED', headline: 'Build worlds people remember' },
  },
  {
    id: 'schematic-indigo',
    name: 'Schematic Indigo',
    version: 1,
    mode: 'light',
    summary: 'Sistema técnico claro baseado em estrutura, labels monoespaçadas e acento índigo-violeta.',
    tags: ['light', 'technical', 'schematic', 'documentation', 'developer-tools'],
    suitableFor: ['documentação', 'APIs', 'ferramentas dev', 'produtos de engenharia'],
    direction: ['A estrutura deve ser visível: grades, relações e hierarquia ajudam a leitura.', 'Labels técnicas usam mono; explicações permanecem em sans confortável.', 'O índigo destaca links, seleção e fluxo, sem colorir superfícies inteiras.'],
    colors: { canvas: '#F4F5F8', surface: '#FFFFFF', elevated: '#FFFFFF', text: '#171A24', muted: '#687080', border: '#D5D9E2', primary: '#5C4EE5', secondary: '#2C9FA3', danger: '#C63F52' },
    typography: { display: 'Geist', body: 'Inter', mono: 'Geist Mono', displayWeight: 650, bodyWeight: 400, tracking: '-0.025em' },
    geometry: { radius: '8px', controlRadius: '6px', border: '1px', shadow: '0 12px 36px rgba(33, 37, 52, .09)', density: 'dense' },
    layout: ['Grid de documentação com navegação lateral, conteúdo e índice local.', 'Diagramas alinham nós a uma malha de 8px.', 'Exemplos de código nunca ultrapassam a largura do conteúdo.'],
    components: ['Código tem botão de copiar, linguagem e foco visível.', 'Callouts usam ícone, título e borda lateral sem depender só de cor.', 'Árvores e listas mostram claramente expansão e seleção.'],
    motion: ['Expansões de 140–200ms.', 'Linhas de diagrama podem revelar direção uma vez.', 'Scroll de âncora respeita preferência de movimento.'],
    avoid: ['linhas decorativas sem significado', 'texto mono em parágrafos', 'gradientes grandes', 'ícones sem label'],
    preview: { composition: 'schematic', eyebrow: 'SPECIFICATION / V1.4', headline: 'Structure makes complexity legible' },
  },
  {
    id: 'tangerine-ledger',
    name: 'Tangerine Ledger',
    version: 1,
    mode: 'light',
    summary: 'Fintech editorial de alto impacto com superfícies tangerina, creme e tipografia oversized.',
    tags: ['light', 'finance', 'editorial', 'bold', 'orange'],
    suitableFor: ['fintech', 'investimentos', 'relatórios', 'landing pages de produto'],
    direction: ['A marca é confiante e otimista, sem parecer promocional demais.', 'Tangerina cria blocos editoriais; áreas transacionais usam creme calmo.', 'Números grandes são acompanhados por contexto, período e unidade.'],
    colors: { canvas: '#F7E8D1', surface: '#FFF4E5', elevated: '#FFFFFF', text: '#281A12', muted: '#7A675B', border: '#D9BFA7', primary: '#E85D24', secondary: '#7E4DE8', danger: '#B93642' },
    typography: { display: 'Archivo Black', body: 'Manrope', mono: 'DM Mono', displayWeight: 800, bodyWeight: 400, tracking: '-0.045em' },
    geometry: { radius: '14px', controlRadius: '999px', border: '1px', shadow: '0 20px 55px rgba(109, 55, 25, .13)', density: 'comfortable' },
    layout: ['Hero tipográfico ocupa grande parte da primeira dobra.', 'Métricas alternam entre cards claros e blocos tangerina.', 'Tabelas financeiras permanecem neutras e altamente legíveis.'],
    components: ['CTAs escuros sobre tangerina preservam contraste.', 'Cards de saldo usam números tabulares.', 'Estados positivos e negativos incluem sinal e texto, não apenas cor.'],
    motion: ['Números atualizam sem roleta longa.', 'Cards respondem em 180–240ms.', 'Transições de página usam wipes simples apenas em marketing.'],
    avoid: ['verde/vermelho sem símbolo', 'laranja em tabelas inteiras', 'jargão sem explicação', 'números sem unidade'],
    preview: { composition: 'finance-bold', eyebrow: 'CAPITAL / BRIEF 04', headline: 'Money, made unmistakable' },
  },
  {
    id: 'monochrome-frame',
    name: 'Monochrome Frame',
    version: 1,
    mode: 'light',
    summary: 'Estúdio silencioso em preto e branco, tipografia pesada e whitespace cinematográfico.',
    tags: ['light', 'monochrome', 'portfolio', 'studio', 'minimal'],
    suitableFor: ['agências', 'fotografia', 'arquitetura', 'portfólios'],
    direction: ['O trabalho é protagonista; a interface funciona como moldura.', 'Escala tipográfica e espaço substituem cor decorativa.', 'Um único acento opcional pode existir para estado ou chamada principal.'],
    colors: { canvas: '#F3F2EE', surface: '#FBFAF7', elevated: '#FFFFFF', text: '#111111', muted: '#77746E', border: '#CECCC5', primary: '#111111', secondary: '#D9FF43', danger: '#B4373F' },
    typography: { display: 'Archivo Black', body: 'Helvetica Neue', mono: 'IBM Plex Mono', displayWeight: 800, bodyWeight: 400, tracking: '-0.05em' },
    geometry: { radius: '0px', controlRadius: '999px', border: '1px', shadow: '0 18px 54px rgba(17, 17, 17, .08)', density: 'spacious' },
    layout: ['Grid editorial assimétrico com margens generosas.', 'Projetos alternam escala e alinhamento para criar ritmo.', 'Descrição nunca compete com a imagem principal.'],
    components: ['Links de projeto usam seta e sublinhado preciso.', 'Filtros são texto selecionável, não pílulas coloridas.', 'Imagens mantêm proporção e crédito opcional.'],
    motion: ['Imagens ampliam 2–3% em 500ms.', 'Títulos entram em grupos discretos.', 'Sem cursores customizados obrigatórios.'],
    avoid: ['cards arredondados genéricos', 'muitas cores', 'sombras profundas', 'carrossel automático'],
    preview: { composition: 'portfolio', eyebrow: 'SELECTED WORK / 01—06', headline: 'Less interface. More work.' },
  },
  {
    id: 'crimson-paper',
    name: 'Crimson Paper',
    version: 1,
    mode: 'light',
    summary: 'Minimalismo de papel claro onde apenas a ação principal ganha presença tátil carmesim.',
    tags: ['light', 'minimal', 'paper', 'tactile', 'product'],
    suitableFor: ['serviços premium', 'produtos focados', 'editorial', 'landing pages'],
    direction: ['Quase tudo permanece plano e silencioso.', 'A ação principal é o único objeto com profundidade tátil forte.', 'Hierarquia depende de tipografia, alinhamento e contraste.'],
    colors: { canvas: '#F1EEE8', surface: '#FAF8F3', elevated: '#FFFFFF', text: '#201D1B', muted: '#756E68', border: '#D8D1C9', primary: '#A8172E', secondary: '#D7A43B', danger: '#A8172E' },
    typography: { display: 'Instrument Serif', body: 'Inter', mono: 'DM Mono', displayWeight: 500, bodyWeight: 400, tracking: '-0.03em' },
    geometry: { radius: '8px', controlRadius: '7px', border: '1px', shadow: '0 5px 0 #6E0E1E', density: 'comfortable' },
    layout: ['Uma coluna principal forte com detalhes em segunda coluna.', 'Seções são separadas por espaço ou hairlines.', 'Máximo de um CTA primário por viewport.'],
    components: ['Botão primário carmesim tem base deslocada e estado pressionado.', 'Campos são planos, com underline ou borda fina.', 'Cards só existem quando há agrupamento semântico real.'],
    motion: ['Botão tátil desce 3px ao pressionar.', 'Demais elementos usam fade de 180–260ms.', 'Sem efeitos contínuos.'],
    avoid: ['sombras em todos os cards', 'mais de um botão tátil por seção', 'fundos vermelhos extensos', 'bordas decorativas'],
    preview: { composition: 'editorial-minimal', eyebrow: 'A QUIET STANDARD', headline: 'One clear action changes everything' },
  },
];

module.exports = Object.freeze(presets.map((preset) => Object.freeze(preset)));
