'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {readSse}=require('../main/adapters/network/sse');const {retryAfterMs,normalizedRps,requestScope}=require('../main/adapters/network/rate-limiter');const {FetchPolicy}=require('../main/adapters/network/fetch-policy');const {OpenAIAdapter}=require('../main/domains/ai-providers/openai-adapter');const {AnthropicAdapter,convertToAnthropic}=require('../main/domains/ai-providers/anthropic-adapter');
function streamResponse(chunks,options){const encoder=new TextEncoder();return{ok:options&&options.ok===false?false:true,status:options&&options.status||200,headers:{get:(name)=>options&&options.headers&&options.headers[name.toLowerCase()]||null},text:async()=>options&&options.text||'',body:new ReadableStream({start(controller){for(const chunk of chunks)controller.enqueue(encoder.encode(chunk));controller.close()}})}}
test('SSE recompõe linhas fragmentadas, CRLF e tail sem newline',async()=>{const values=[];await readSse(streamResponse(['da','ta: one\r\n','data: tw','o']),value=>values.push(value));assert.deepEqual(values,['one','two'])});
test('rate helpers limitam valores e scope não expõe chave',()=>{assert.equal(normalizedRps({requestRps:.01}),.1);assert.equal(normalizedRps({requestRps:999}),100);assert.equal(retryAfterMs('1.5',0),1500);assert.equal(retryAfterMs('invalid',0),0);const scope=requestScope({provider:'openai',baseUrl:'HTTPS://API/X/','apiKey':'segredo'});assert.doesNotMatch(scope,/segredo/);assert.match(scope,/openai\|https:\/\/api\/x/)});
test('FetchPolicy repete um único 429 somente com RPS explícito',async()=>{let calls=0,waits=0;const responses=[streamResponse([],{ok:false,status:429,headers:{'retry-after':'0'}}),streamResponse([])];responses[0].body={cancel:async()=>{}};const policy=new FetchPolicy({fetch:async()=>responses[calls++],limiter:{wait:async()=>{waits++}},clock:{now:()=>0,setTimeout:(fn)=>{fn();return 1},clearTimeout:()=>{}}});const result=await policy.request({requestRps:1,provider:'x',baseUrl:'x'},'url',{});assert.equal(result.ok,true);assert.equal(calls,2);assert.equal(waits,2)});
test('OpenAI adapter preserva thinking, tool fragments e usage em SSE quebrado',async()=>{const events=[{choices:[{delta:{content:'Olá <thi'}}]},{choices:[{delta:{content:'nk>penso</think> fim'}}]},{choices:[{delta:{tool_calls:[{index:0,id:'call1',function:{name:'read_file',arguments:'{"pa'}}]}}]},{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'th":"a.js"}'}}]}}]},{usage:{prompt_tokens:10,completion_tokens:4,total_tokens:14},choices:[]}];const wire=events.map(x=>'data: '+JSON.stringify(x)+'\n').join('')+'data: [DONE]\n',chunks=[wire.slice(0,17),wire.slice(17,53),wire.slice(53)];const requests=[],tokens=[],thinking=[];const adapter=new OpenAIAdapter({fetchPolicy:{request:async(...args)=>(requests.push(args),streamResponse(chunks))},clock:{now:(()=>{let n=0;return()=>++n})()}});const result=await adapter.turn({config:{baseUrl:'https://api',model:'m',temperature:.5},messages:[],tools:[],onToken:t=>tokens.push(t),onThink:t=>thinking.push(t)});assert.equal(result.text,'Olá  fim');assert.equal(thinking.join(''),'penso');assert.deepEqual(JSON.parse(result.toolCalls[0].arguments),{path:'a.js'});assert.equal(result.usage.total_tokens,14);assert.match(requests[0][1],/chat\/completions$/)});
test('Anthropic conversion preserva system, images e tool results',()=>{const converted=convertToAnthropic([{role:'system',content:'sys'},{role:'user',content:[{type:'text',text:'veja'},{type:'image_url',image_url:{url:'data:image/png;base64,AAA'}}]},{role:'assistant',content:null,tool_calls:[{id:'x',function:{name:'read',arguments:'{"p":1}'}}]},{role:'tool',tool_call_id:'x',content:'ok'}]);assert.equal(converted.system,'sys');assert.equal(converted.messages[0].content[1].type,'image');assert.equal(converted.messages[1].content[0].type,'tool_use');assert.equal(converted.messages[2].content[0].type,'tool_result')});
test('Anthropic adapter monta tool use fragmentado e usage normalizado',async()=>{const events=[{type:'message_start',message:{usage:{input_tokens:7}}},{type:'content_block_delta',index:0,delta:{type:'text_delta',text:'feito'}},{type:'content_block_start',index:1,content_block:{type:'tool_use',id:'t1',name:'grep'}},{type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:'{"q":"x"}'}},{type:'message_delta',usage:{output_tokens:3}}],wire=events.map(x=>'data: '+JSON.stringify(x)+'\n').join('');const adapter=new AnthropicAdapter({fetchPolicy:{request:async()=>streamResponse([wire.slice(0,31),wire.slice(31)])},clock:{now:()=>10}});const result=await adapter.turn({config:{baseUrl:'https://anthropic',apiKey:'k',model:'claude'},messages:[{role:'user',content:'oi'}],tools:[],onToken:()=>{},onThink:()=>{}});assert.equal(result.text,'feito');assert.deepEqual(result.usage,{prompt_tokens:7,completion_tokens:3,total_tokens:10});assert.deepEqual(JSON.parse(result.toolCalls[0].arguments),{q:'x'})});
test('adapter devolve parcial marcado quando signal é abortado',async()=>{const controller=new AbortController(),adapter=new OpenAIAdapter({fetchPolicy:{request:async()=>{controller.abort();throw new Error('abort')}}});const result=await adapter.turn({config:{baseUrl:'x',model:'m'},messages:[],tools:[],signal:controller.signal});assert.equal(result.aborted,true)});
