'use strict';
const { redactString }=require('../../core/redaction');const { contextLimits }=require('./budget');const { scopeKey }=require('../workspace/workspace-path');
function compactText(value,max){let text;try{text=typeof value==='string'?value:JSON.stringify(value||'')}catch(_){text=String(value||'')}text=redactString(text).replace(/((?:api[_-]?key|token|password|senha)\s*[:=]\s*)[^\s,;]+/gi,'$1[oculto]').replace(/\s+/g,' ').trim();return text.length>max?text.slice(0,max)+'…':text}
// Projeto lógico do turno: um subagente isolado roda em worktree Git temporário — o caminho
// físico muda, o projeto não. Por isso projectRoot vence o workspace da vez.
function scopeHere(session,config){return scopeKey((session&&session.projectRoot)||(config&&config.workspace))}
// Só o diário registrado NESTE projeto. Entrada sem carimbo é anterior à separação: passa
// apenas quando a conversa também não tem projeto conhecido (aí não há como estar misturada).
function entriesForWorkspace(list,session,config){const here=scopeHere(session,config),chatWs=scopeKey(session&&session.chatWorkspace);return(list||[]).filter((e)=>{const stamped=scopeKey(e&&e.ws);return stamped?stamped===here:!chatWs||chatWs===here})}
function renderLedger(session,config){if(!session.ledger||!session.ledger.length||!config.workspace||config.memoryEnabled===false)return'';const scoped=entriesForWorkspace(session.ledger,session,config);if(!scoped.length)return'';const text=scoped.slice(-12).map((e)=>[`## ${String(e.at||'').slice(0,16).replace('T',' ')} · ${e.mutations||0} mutação(ões) · ${e.status||'completed'}`,`Objetivo: ${e.goal||'(não registrado)'}`,e.filesChanged&&e.filesChanged.length?`Alterados: ${e.filesChanged.join(', ')}`:'',e.filesRead&&e.filesRead.length?`Lidos: ${e.filesRead.slice(0,12).join(', ')}`:'',e.verification&&e.verification.length?`Verificações: ${e.verification.map(v=>`${v.ok?'✓':'✗'} ${v.command}`).join('; ')}`:'',e.failures&&e.failures.length?`Falhas: ${e.failures.map(f=>`${f.tool}${f.target?` (${f.target})`:''}: ${f.summary}`).join('; ')}`:''].filter(Boolean).join('\n')).join('\n\n');const max=Math.min(18000,Math.max(4000,Math.floor(contextLimits(config).window*.035*3.6)));return text.length>max?text.slice(-max):text}
function renderWorklog(session,config){if(!session.worklog||!session.worklog.length||!config.workspace||config.memoryEnabled===false)return'';const scoped=entriesForWorkspace(session.worklog,session,config);if(!scoped.length)return'';const text=scoped.slice(-10).map((e)=>[`## ${String(e.at||'').slice(0,16).replace('T',' ')} — ${e.goal||'turno técnico'} [${e.status||'completed'}]`,e.filesChanged&&e.filesChanged.length?`Arquivos alterados: ${e.filesChanged.join(', ')}`:'',e.verification&&e.verification.length?`Verificações: ${e.verification.map(v=>`${v.ok?'✓':'✗'} ${v.command}`).join('; ')}`:'',(e.tools||[]).map(t=>`${t.status==='success'?'✓':'✗'} ${t.tool}${t.target?` (${t.target})`:''}: ${t.summary}`).join('\n'),e.outcome?`Resultado: ${e.outcome}`:''].filter(Boolean).join('\n')).join('\n\n');const max=Math.min(32000,Math.max(6000,Math.floor(contextLimits(config).window*.06*3.6)));return text.length>max?text.slice(-max):text}
module.exports={compactText,renderLedger,renderWorklog,entriesForWorkspace};
