'use strict';
const nodeFs=require('fs'),nodePath=require('path');
class ProjectContextService{
 constructor(options){const opts=options||{};this.fs=opts.fs||nodeFs.promises;this.path=opts.path||nodePath;this.detectStack=opts.detectStack||(()=>({}));this.clock=opts.clock||{now:()=>Date.now()};this.ttlMs=Number(opts.ttlMs)||20000;this.maxEntries=Number(opts.maxEntries)||6;this.cache=new Map()}
 async read(file,max){try{return(await this.fs.readFile(file,'utf8')).trim().slice(0,max)}catch(_){return''}}
 async rules(workspace){const names=['CLAUDE.md','AGENTS.md','.cursorrules',this.path.join('.github','copilot-instructions.md')],parts=[];let total=0;for(const name of names){const text=await this.read(this.path.join(workspace,name),8000);if(text){parts.push(`### ${name}\n${text}`);total+=text.length;if(total>16000)break}}return parts.join('\n\n')}
 async get(workspace){const root=String(workspace||'');if(!root)return{workspace:'',rules:'',design:'',memory:'',stack:{},meta:{projects:[],scripts:[],envFiles:[],envKeys:[],hasVenv:false}};const hit=this.cache.get(root),now=this.clock.now();if(hit&&now-hit.at<this.ttlMs)return hit.value;const [rules,design,memory,stack]=await Promise.all([this.rules(root),this.read(this.path.join(root,'DESIGN.md'),24000),this.read(this.path.join(root,'.lumi-memory.md'),64000),Promise.resolve(this.detectStack(root))]);const projects=Array.isArray(stack&&stack.projects)?stack.projects:[],meta={projects,scripts:projects.flatMap(p=>(p.scripts||[]).map(s=>`${p.path}:${s}`)).slice(0,60),envFiles:projects.flatMap(p=>p.envFiles||[]).slice(0,40),envKeys:[...new Set(projects.flatMap(p=>(p.envFiles||[]).flatMap(f=>f.keys||[])))].slice(0,80),hasVenv:projects.some(p=>p.hasVenv)};const value={workspace:root,rules,design,memory,stack:stack||{},meta};this.cache.set(root,{at:now,value});while(this.cache.size>this.maxEntries)this.cache.delete(this.cache.keys().next().value);return value}
 invalidate(workspace){if(workspace)this.cache.delete(String(workspace));else this.cache.clear()}
}
module.exports={ProjectContextService};
